spec-version: 0.36.0
name: colour-guesser
version: 0.1.0.0
ghc-options: -Wall -Werror -threaded
default-extensions:
  - ScopedTypeVariables
dependencies:
  - base >= 4.13 && < 5
  - genetic
  - MonadRandom
  - vector
library:
  source-dirs: src
executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - containers
    - colour-guesser
    - gi-gtk4
    - haskell-gi-base
    - optparse-applicative
    - threepenny-gui
tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - colour-guesser
      - hspec
      - hspec-expectations
      - QuickCheck
